# fly.toml app configuration file generated for codako-prod on 2024-09-09T14:58:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
primary_region = 'atl'

[build]

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
